def scope():
	x = 1
	print('Hello World!')
	print(x)


# print(x)	terar erro pois a variavel x esta sendo chamada fora do escopo da função
scope()

